Unity-Technologies/com.unity.multiplayer.samples.coop

.gitattributes
README.md

Suggested updates to the readme based on information gained writing the getting-started guide.

Briancoughlin patch 2

---

Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
Assets/BossRoom/Scripts/Server/Game/Action/StealthModeAction.cs
Assets/BossRoom/Scripts/Server/Game/Character/AIBrain.cs
Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkCharacterState.cs

This missing fix slipped through and gives the wrong message that NetworkVariableBool is broken (which is not the case). Removing that usage now to not mislead users.

Refactor for stealth state, should use bool, not byte

---

Assets/BossRoom/Scripts/Client/AnimationCallbacks/AnimatorTriggeredSpecialFX.cs

This is a simple enhancement to `AnimatorTriggeredSpecialFX` to let you specify what bone to parent a graphical prefab to (instead of being parented to the root GameObject).
This is needed for a few special effects, such as the "eyes glow red" effect of the boss, the Mage character's staff-glow effect, and various weapon-trail effects.
For completeness, I added the code to both the "on enter node" and "on exit node" logic, although we only intend to use it on the on-enter-node case.

Feature/parenting for animation-triggered FX

---

Assets/BossRoom/Scripts/Client/UI/StartupUI.cs

A leftover line caused max-volume to be capped at whatever it was when the game started up. (Volume is controlled by an `AudioMixer` now, and this old line was directly changing the `AudioListener` volume... but only at startup, since the other lines that directly change `AudioListener` volume have been correctly removed.)
Edit: previously thought this was a merge issue from the release->develop merge, but I realized it's a bug in both branches, so not a merge problem

Bug fix: volume controller problems

---

Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs

The comments about this hacky function have already been removed, but the function itself remained (but was un-called). Since this is the MLAPI initialization code path, we want that to be as unambiguous as possible.

Feature/remove unused work-around function (trivial)

---

Assets/BossRoom/Scripts/Client/Net/ClientGameNetPortal.cs
Assets/BossRoom/Scripts/Client/UI/PostGameUI.cs
Assets/BossRoom/Scripts/Server/Net/ServerGameNetPortal.cs
Assets/BossRoom/Scripts/Shared/Net/GameNetPortal.cs

If you hit "Return to Main Menu" in the post-game scene, you couldn't reliably play again. This was because GameNetPortal wasn't properly cleaning up its state (either ServerGameNetPortal or ClientGameNetPortal, but Server was more serious, because it was tracking a bunch of dictionaries that needed to get wiped between sessions). 
I've done a pretty strenuous test with two clients and host, having one player be host multiple times, then having them alternate. I could consistently play and re-enter the match.

[GOMPS-355] Bugfix/multiple sessions fail

---

Assets/BossRoom/Scripts/Client/Game/Action/FXProjectileTargetedActionFX.cs

After the recent mage-bolt PR, mage-bolts can no longer go through walls. The action-anticipation system was merged separately and did not take this scenario into account, so mages can still see their mage-bolts going through walls (harmlessly) although other players will see the correct action.
This PR adds the needed Anticipation logic for `FXProjectileTargetedActionFX` so that it can properly predict when a mage-bolt is going to slam into a wall.

Feature/Fix anticipation for mage-bolts through walls

---

Assets/BossRoom/Prefabs/State/BossRoomState.prefab
Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
Assets/BossRoom/Scripts/Server/ServerTestingHotkeys.cs
Assets/BossRoom/Scripts/Server/ServerTestingHotkeys.cs.meta

Moves the testing commands that were hacked into `ServerBossRoomState` into their own separate component on the same prefab.

(Cleanup) Isolate testing commands

---

Assets/BossRoom/Prefabs/UI/PartyHUD.prefab

PartyHUD prefab had gotten messed up, so that if you had 3 or more players, you would hit an unassigned entry in the array on startup, causing an NRE on all clients. This happened at a vulnerable time on the host, as well, causing the game to completely fail to initialize (no dynamic entities spawned).
For some reason, Unity shuffled the prefab a good bit, but the only actual change is to the `m_AllyPanel` serialized array.

fix multiplayer crash with 3+ players

---

Assets/BossRoom/Scenes/MainMenu.unity

This is GOMPS-474. Two separate GameObjects had been duplicated unnecessarily in the MainMenu scene.

removing duplicate prefabs from main menu scene

---

Assets/BossRoom/Prefabs/Character/Player.prefab
Assets/BossRoom/Scripts/Server/Game/AIState/IdleAIState.cs
Assets/BossRoom/Scripts/Server/Game/Character/PlayerServerCharacter.cs
Assets/BossRoom/Scripts/Server/Game/Character/PlayerServerCharacter.cs.meta
Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
Assets/BossRoom/Scripts/Server/Game/Entity/ServerWaveSpawner.cs
Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs

Edit: moving the static list of `ServerCharacters` into a separate class that ONLY tracks the `ServerCharacters` for players. Refactored code that iterates players to use this new list.
---
`ServerCharacter` had a static list of all active `ServerCharacters`. This turns out to be basically redundant with MLAPI's `NetworkSpawnManager` which already provides a list of these. The static list had already been phased out in all but one place, so I've refactored the last remaining spot.
But note that this code is slower than before: `NetworkSpawnManager` gives us a listing of `NetworkObject`s, so we have to call `GetComponent<ServerCharacter>()` on each one to get the actual character info. And unfortunately the last remaining use of this list is in code that gets called many times every frame. …

(Cleanup) (feedback needed) Remove redundant list of ServerCharacters

---

Assets/BossRoom/Scripts/Server/ServerTestingHotkeys.cs

Change the testing commands to explicitly spawn test entities with the "don't destroy on load" parameter set to true.
(This fixes null-ref exceptions when you have a test-spawned monster selected when the game switches to the game over scene.)

Bugfix: testing commands created monsters that were not destroyed on new scene

---

Assets/BossRoom/Prefabs/Game/EnemySpawner.prefab
Assets/BossRoom/Scripts/Server/Game/AIState/IdleAIState.cs
Assets/BossRoom/Scripts/Server/Game/Character/AIBrain.cs
Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
Assets/BossRoom/Scripts/Server/Game/Entity/ServerWaveSpawner.cs

Adds new settings to the ServerWaveSpawner. These new settings will be tuned and tweaked in the final "balance pass". This is just the code pass, so the values I entered are placeholders. 
(The ultimate goal is to make the spawners relevant to the demo! Right now you can simply ignore the spawners and attack the boss, because they're off in the corners and the imps don't aggro. This is also one of the places we can dynamically tune the game difficulty based on number of players, so we want to demonstrate that.)
*Feature Additions*
- The max # of simultaneous spawns is now determined based on the number of players
- Spawner can now override the spawned entity's detection range
- New option makes spawner's player-detector skip over players who are Stealthy
*Other*
- Added more …

Feature/Spawner Improvements

---

Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/crystal/DestroyedCrystal.prefab
Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pillar/env_pillar2_break_parent.prefab
Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pots/env_pot_break_parent.prefab
Assets/BossRoom/Scenes/BossRoom.unity
ProjectSettings/TagManager.asset

Adds a new Layer to the project, "Debris". The "broken" versions of pots, pillars, and crystals are now in the Debris layer. Since projectiles and attacks check for the "PC" "NPC" and "Ground" layers, this fixes the issue. 
(Previously these "broken versions" were using the NPCs layer.)

Bugfix/broken pieces should not be hit by attacks/projectiles [GOMPS-461]

---

Assets/BossRoom/GameData/Action/Archer/ArcherChargedShot.asset

(I'm not sure what the bug number for this is, sorry!)
Bug: if you play as an Archer and press the "1" key really fast, you can end up with the character stuck in the "charging up" animation permanently (well, until you use another charged shot).
This is caused by the animator triggers being reset at extreme speed, so that the stop and start triggers overlap. Rather than trying to change the trigger logic, though, I think the right fix is just to prevent you from firing so many charged shots! (Since pressing "1" really fast currently gives you an ultra death ray of infinite arrows.)
Now that we have the `ReuseTime` field this is easy. This PR changes Charged Shot's `ReuseTime` from 0 secs to a 0.7 secs

Bugfix: archer charged shot can be spammed

---

Assets/BossRoom/Scripts/Client/UI/RoomNameBox.cs

We didn't have a repro for this, but I'm sure it's some odd boundary condition either on starting or stopping. We also didn't have exact knowledge of which object was null, but the line number showed it happening on the if statement I modified, so I changed the statement to be very conservative. 
fixing: GOMPS-458

fixing NRE in RoomNameBox

---

Assets/BossRoom/Scripts/Shared/Net/NetworkStats.cs

GOMPS-351: I have added "Type: Host" or "Type: Client" to the NetworkStats UI, and collected the setup code for a text line into a helper method.

enhancing NetworkStats to also have the host/player type (GOMPS-351)

---

LICENSE.md
Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/LICENSE.md

Updates in this PR:
- Update LICENSE in repo and package to strictly UCL. Ticket GOMPS-494 , verified with Legal.
- Update changelog to include 0.1.1 hotfix.
- Added potential hotfix 0.1.2 entry for the UCL license. Can remove that entry if a hotfix is not cut.
Currently entering this PR against `master` branch. Can also provide a PR to `develop` if needed.

docs: License UCL update and changelog additions

---

Assets/BossRoom/Scripts/Client/Net/ClientGameNetPortal.cs

In MLAPI, on the Host, `IsClient` returns true. But `IsConnectedClient` returns false. Doesn't seem right. At any rate, I've fixed it. Now it has the correct behavior on both hosts and clients. 
This was causing an issue where whenever any player left, the Host was booted to Main Menu.

fixing issue where host disconnects on player leaving.

---

Assets/BossRoom/Scripts/Client/Game/Action/FXProjectileTargetedActionFX.cs
Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
Assets/BossRoom/Scripts/Server/Game/Action/FXProjectileTargetedAction.cs

Many actions can cause the player to "look like" they're hitting another player (e.g. selecting an ally and clicking the Attack button will make your ally play a hit-react animation) but that's just amusing fluff... the problem is that mage bolt did actual damage to other players. This is fixed.
Also fixed: if the target of the mage bolt had disappeared since the attack was queued, it was simply aborted because it had no target. Now, the attack is not aborted, and turns into a "missed" bolt. (To do this, the client sends the click-position along with all mage-bolt attacks.)

Bugfix: Fix mage-bolt friendly fire [GOMPS-299]

---

Assets/BossRoom/Scripts/Client/Game/Action/AoeActionInput.cs
Assets/BossRoom/Scripts/Client/Game/Action/ChargedActionInput.cs
Assets/BossRoom/Scripts/Client/Game/Action/ChargedShieldActionFX.cs
Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
Assets/BossRoom/Scripts/Shared/Game/Action/BaseActionInput.cs

The tank's "Charged Shield" action did not support Anticipation (i.e. playing a client-side action before the server tells us to, for more reactive gameplay). This is fixed by this PR.
Actions with special input-handlers didn't trigger the same client-side events that other actions did. To ensure that all actions sent to the server also send appropriate events to the client, I've routed a new callback into `BaseActionInput`, which derived versions can use to send input correctly. 
After this is done, the actual custom Anticipation logic for `ChargedShieldActionFX` is trivial, and just like other Actions.
Also fixed issue where you could sometimes get the animations out of sync if you spam-clicked the shield charge button. (By resetting the end-animation trigger before we begin.)

Feature/Shield-Charge attack has anticipation anim [GOMPS-472]

---

Assets/BossRoom/Scripts/Shared/Game/UI/UIStateDisplayHandler.cs

Because order of object `Destroy()`ing isn't guaranteed, sometimes a character's visualization object is destroyed before the health-bar UI elements that are tracking it. Added a null check. 
I've seen this error myself occasionally, but could not reproduce it on demand. I suspect this is a stop-play-in-editor situation, because in a standalone, I think both the child and parent objects should be destroyed before the next `LateUpdate()` is called. In any case I'm fairly confident this will address the problem.

Fix occasional NREs during object destruction [GOMPS-502][GOMPS-503]

---

Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs

Fixes a null-reference error message that can happen when you stop Play mode in the editor. 
(I'm not sure if this one is tracked in jira. Judging by the code-comments, I think we already tried to fix it, but I got the error again, so the previous check didn't quite get the job done.)

Feature/another null-check to fix NRE in editor shutdown

---

Assets/BossRoom/Scripts/Client/Game/Action/ActionVisualization.cs

- if an anticipated action's `Start()` returns false, we should remove the action
- do not call `Update()` on an anticipated action (until it stops being anticipated)
This addresses [GOMPS-505]: Archer's Volley generates "This should not execute" exceptions

Feature/Anticipation logic tweaks [GOMPS-505]

---

Assets/BossRoom/Models/CharacterSet.fbx.meta
Assets/BossRoom/Prefabs/CharGFX/BossGraphics.prefab
Assets/BossRoom/Scripts/Client/AnimationCallbacks/BossDeathHelmetHandler.cs
Assets/BossRoom/Scripts/Client/AnimationCallbacks/BossDeathHelmetHandler.cs.meta

The boss's helmet appears to "jiggle" on the ground while the boss throws his temper-tantrum. This isn't a problem with the animation per se -- the helmet is stationary in the FBX file. Most of the jitter comes from animation compression, but even when turning that off, there is still a slight jiggle, which is just caused by 32-bit-float roundoff. The helmet is parented deep in the bone hierarchy, so when the boss is moving around, it's very difficult to keep the child transform perfectly still.
The best fix we could see is to de-parent the boss's helmet when it hits the ground. The death animation now generates an event at the proper moment, and a new component on the boss handles that event by disconnecting the helmet (and cleaning it up on destroy).

Fix boss-death helmet jiggle by deparenting helmet [GOMPS-463]

---

Assets/BossRoom/Prefabs/BossRoomHudCanvas.prefab
Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/crystal/DestroyedCrystal.prefab
Assets/BossRoom/Prefabs/UI/Hero Action Bar.prefab
Assets/BossRoom/Prefabs/UI/Hero Emote Bar.prefab
Assets/BossRoom/Scripts/Client/Game/Action/AoeActionInput.cs
Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
Assets/BossRoom/Scripts/Server/Game/Action/MeleeAction.cs
Assets/BossRoom/VFX/Materials/FX_Crystal_Broken.mat
Assets/BossRoom/VFX/Materials/FX_Crystal_Broken.mat.meta

Some easy-to-implement polish tasks that came about from feature-complete playtesting. These are intended to improve the game's first impression.
- crystals are too shiny and weird-looking when they're broken 
- (broken bits now use a different material)
- if you're standing still and trying to melee an enemy, you should turn to face the enemy so you can actually hit them
- note that this is overridden by movement, so if player is already charging forward when they perform a melee action, they'll still melee in the direction they're moving
- when using the archer's AoE ability, the reticule should wait for a real mouse-click, not just a mouse-release
- (it already worked this way if you used the keyboard key to activate it, so this is just making mouse and keyboard orthogonal)
- make the …

Minor gameplay polish tasks

---

Assets/BossRoom/Scripts/Client/Game/Action/ChargedLaunchProjectileActionFX.cs
Assets/BossRoom/Scripts/Client/Game/Action/FXProjectileTargetedActionFX.cs
Assets/BossRoom/Scripts/Server/Game/Entity/ServerWaveSpawner.cs
Assets/BossRoom/Scripts/Shared/Game/Action/ActionRequestData.cs

* Fixes a case where some imps were leaking out of the BossRoom scene and contaminating the postgame scene. This was invisible unless somebody tried to join post-game, and then those imps would get instantiated on the joining client and throw exceptions (the issue was that Imp Spawners weren't setting imps to `deleteWithScene=true`)
* [GOMPS-513] Fixes an NRE with ChargedShot. I did this by making a throw-away alloc, but at the rate that these objects get instantiated (one every couple seconds, probably), I didn't think it was a big deal. 
* [GOMPS-228] Some open PR style feedback.

[GOMPS-228][GOMPS-513] fixing handful of remaining bugs

---

Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkCharacterState.cs

I have moved position and rotation to the MLAPI PositionUpdate channel, which is {Unreliable,Sequenced}. This significantly improves the user experience in high packet loss scenarios. 
I tested with clumsy, 50ms of bi-directional latency (measuring 250ms RTT in game), and 10% packet loss. Without this change, movement and camera were both horribly janky. After the change, the experience was largely tolerable, with occasional subtle disruptions (not too bad, considering 10% packet loss is pretty rough!)

[GOMPS-522] fixes character jitter in high packet loss scenarios

---

Assets/BossRoom/Prefabs/UI/PartyHUD.prefab

In the PartyHUD, all AllyHUD buttons after the 1st one had their "OnClick" Unity event empty. I assume this was some kind of weird merge problem. To reproduce the problem you needed at least 3 players, so you could click on "Player 3" (the 2nd ally, who will be the first person to show the problem). 
I hooked AllyHUD 2-7 back up in the PartyHUD prefab, and verified that the exception no longer occurs.

Bugfix/gomps 521 fixes ArgumentNullException

---

Assets/BossRoom/Prefabs/CharGFX/BossGraphics.prefab

If the boss is stunned while performing their trample attack, the trample particles were not aborted. This is fixed with a data change, by setting the "how long can we abort this graphic" setting to a very high number. (We use 999,999 seconds as a way to denote "forever".)

Bugfix: boss's "charging" particles not canceled when stunned

---

Assets/BossRoom/Scripts/Client/Game/Action/FXProjectileTargetedActionFX.cs

This fixes an exception that showed up during extreme network scenario testing. We were incorrectly using null propagation on a Unity object, and then trying to get a transform off a deleted object, which didn't work so well.

[GOMPS-532] removing incorrect use of null propagation on Unity object

---

.github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md

A template for future Pull Requests. 
Adds description and issue/Jira ticket fields to help with team collaboration and tracking.
GOMPS-531
https://unity3d.atlassian.net/browse/GOMPS-531

Uploading pull-request-template

---

Packages/manifest.json
Packages/packages-lock.json

MLAPI v0.1-experimental is fetched through internal Unity Package Manager registry, namely `com.unity.multiplayer.mlapi`.

fetching MLAPI experimental package through registry

---

Assets/BossRoom/Prefabs/NetworkingManager.prefab

Simple increment to photon realtime transport's `Send Queue Batch Size` field. This resolves a breaking issue on Photon that prevented players from entering BossRoom scene successfully.

photon transport send queue batch size incremented to 8192

---

Packages/manifest.json
Packages/packages-lock.json

Jira task [here](https://unity3d.atlassian.net/browse/GOMPS-525). Photon has been upgraded to version `e47ee18972b110a689c23d6ffc0e5994d18e9eb2`. Photon-related errors are not logged when pulling network cable.
However, there are still game-side errors that are logged on the host when pulling the network cable. That's tracked [here](https://unity3d.atlassian.net/browse/GOMPS-564) for a follow-up PR.

photon version upgrade

---

Assets/BossRoom/Prefabs/Character/Character.prefab
Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacterMovement.cs
Assets/BossRoom/Scripts/Shared/Game/Entity/NetworkCharacterState.cs

Jira task [here](https://unity3d.atlassian.net/browse/GOMPS-567).
- Characters (`Player`, `Imp`, `Boss`) have now a `NetworkTransform` component, while `ClientGenericMovement` has been removed.
- NetworkVariables for position, rotation & speed have been removed from `NetworkCharacterState`.
- `NetworkTransform` component's `Fixed Sends Per Second` is set to 50 and `Channel` is set to `Position Update`.

networktransform handles players' movement syncing

---

Assets/BossRoom/Prefabs/Character/Imp.prefab
Assets/BossRoom/Prefabs/Character/ImpBoss.prefab
Assets/BossRoom/Scripts/Server/Game/Action/TrampleAction.cs
Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
Assets/BossRoom/Scripts/Server/Game/Entity/DamageReceiver.cs

Fix for [issue](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/issues/364) with the Boss' charge.
- `OnCollisionEnter` wasn't fired on `ServerCharacter` component due to a hierarchy change. Collider component was moved to a child GameObject. `DamageReceiver` instead checks for collisions.
- Null references have been addressed (mostly referencing to `PhysicsWrapper` component).

fixing null refs on boss charge action

---

ProjectSettings/ProjectSettings.asset

This would remove the org and project id's and users would be able to set it up with their own

Remove project and org id's

---

Assets/BossRoom/Scenes/MainMenu.unity

Fixed the Boss Room title not showing up on Mac builds again ([same fix as before](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/387), but redone for the URP version of the main menu scene)
https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/387

Bug Fix: Boss Room title missing

---

Assets/BossRoom/Scripts/Server/Game/Action/LaunchProjectileAction.cs
Assets/BossRoom/Scripts/Shared/Net/NetworkObjectPool.cs

Arrows spawned now correctly despawn when switching scenes.
Fixes issue(s): [MTT-1557](https://jira.unity3d.com/browse/MTT-1557)
1. Start game with an archer
2. Shoot an arrow
3. Go to PostGame scene by pressing 'q', or by dying or killing the boss

Fix: arrows despawning error while switching scenes

---

Assets/BossRoom/Scripts/Shared/Game/UI/Editor/NetworkLatencyWarning.cs
Assets/BossRoom/Scripts/Shared/com.unity.multiplayer.samples.bossroom.shared.asmdef

This PR adds the simulated latency warning that we had with LiteNetLib, but for UTP's simulator tools.
Fixes issue(s): [MTT-1426](https://jira.unity3d.com/browse/MTT-1426)
1. Add simulated latency, jitter or packet loss via UTP's simulator tools
2. Start a game
3. See the warning popup in red on the bottom of the screen

feat: warning when using simulated latency

---

Assets/BossRoom/Scripts/Client/UI/RoomNameBox.cs

This PR removes the room name textbox in the character selection scene when the game uses ip-based connections.
Fixes issue(s): [MTT-1506](https://jira.unity3d.com/browse/MTT-1506)
1. ...
2. ...

fix: removing room name textbox for ip based connections

---

Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs

This PR fixes an issue where the host's session data is not initialized while using URelay or Photon, preventing playing the game.
1. ...
2. ...

fix: inititalize host session data while using URelay or Photon

---

Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs

This PR removes the leftover code and comments from the obsolete workaround for netcode issue 745. The workaround which was to call a coroutine to wait before seating new players was already removed, so we do not need this other part of the workaround.
Fixes issue(s): [MTT-1837](https://jira.unity3d.com/browse/MTT-1837)
1. ...
2. ...

fix: removing workaround for ngo issue 745

---

Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/SessionManager.cs

This PR fixes an issue that caused the host's player name to not be shown on the UI. The name is set in PersistentPlayer's OnNetworkSpawn(), using data from the SessionManager. However, this data was initialized after the call to StartHost(), and the PersistentPlayer was spawned during that call. This was introduced by PR #434 which aimed to solve a different issue, because the host data initialization used data from NetworkManager that was not properly initialized.
Here, the initialization of the host session data has been moved to the connection approval callback, so that it happens before the spawning of NetworkBehaviours, but after the server has been properly initialized.
#434
Fixes issue(s): [MTT-2157](https://jira.unity3d.com/browse/MTT-2157) & …

fix: host name not showing

---

Assets/BossRoom/Scripts/Server/Game/Character/PlayerServerCharacter.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs

This PR makes it so only the server adds entries to the m_ClientSceneMap by registering the callback handling this only on the server. This would previously cause issues since the OnClientSceneChanged is also called on clients. Adding entries on clients doesn't make sense, and causes issues when trying to host a new game afterwards. This new entry prevents spawning the characters in the BossRoom scene, which is triggered when all clients are in the scene, based on this map. So if this map has another entry, it will always be in the wrong scene and the spawn will never be triggered.
This PR also prevents clients from updating the static list of active PlayerServerCharacters, which used to result in a null reference exception when starting a new game in this scenario. …

fix: cannot host a game after having previously played as a client

---

Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pillar/env_pillar2.prefab
Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/pillar/env_pillar2_break_parent.prefab

Fixed the broken material reference on two prefabs used for the boss pillars
Before:
After:
Jira ticket [here](https://jira.unity3d.com/browse/MTT-2292)
1. Get boss to trample a pillar
2. Broken pillar pieces will now have fixed material

Fixed a broken material ref on boss pillars

---

Assets/BossRoom/Scenes/PostGame.unity

This change moves the post game background (it was still there, just off camera) to be lined up with the camera's view, that way you see the background rather than a black screen.
Before:
After:
[Ticket here](https://jira.unity3d.com/browse/MTT-2321)
1. Go to post game (either by losing, winning, using cheat, or host disconnect)
2. Scene background now shows up properly

Fix: Background missing in Post Game scene

---

Assets/BossRoom/Prefabs/NetworkingManager.prefab

Increasing max send queue size to not overflow when there's a pause client side
Reducing timeout to 10 seconds instead of the 30 seconds default.
Putting all values equal between IP and Relay.
This will be cherrypicked to develop as well.
[MTT-2356](https://jira.unity3d.com/browse/MTT-2356)
start client and host, connect to each other, character select, then full game. move around, get some imps following you, generate traffic.
pause client side for more than 10 seconds, wait for host to time you out.
(there's currently a bug open https://jira.unity3d.com/browse/MTT-2703 where the host will vomit errors when a client is disconnected by timeout)

fix: fixing send queue error

---

Assets/BossRoom/Prefabs/UI/SettingsPanelCanvas.prefab
Assets/BossRoom/Scenes/Startup.unity
Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
Assets/BossRoom/Scripts/Client/UI/ConnectionStatusMessageUIManager.cs
Assets/BossRoom/Scripts/Client/UI/ConnectionStatusMessageUIManager.cs.meta
Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
Assets/BossRoom/Scripts/Client/UI/PopupPanel.cs
Assets/BossRoom/Scripts/Client/UI/PopupPanel.cs.meta
Assets/BossRoom/Scripts/Shared/ApplicationController.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs

Cherrypick of changes from PR #494 
1. ...
2. ...

feat: popup panel for connection status messages (#494)

---

Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs

This PR removes regenerating player name after authentication is done.
Fixes issue(s): [MTT-2650](https://jira.unity3d.com/browse/MTT-2650)
1. Open the game, not the name at the bottom of the Lobby UI
2. Create a lobby
3. Select a character, see that your name is the same one as before

fix: username changing before game

---

Assets/BossRoom/Scripts/Server/Game/Character/ServerAnimationHandler.cs

This PR removes the possibility of ServerAnimationHandler setting triggers on NetworkAnimator if it is not the server.
Fixes issue(s): [MTT-2751](https://jira.unity3d.com/browse/MTT-2751)
1. Start a game with at least one client
2. Enter the BossRoom scene
3. See that the warnings are no longer occurring

fix: NetworkAnimator being called on clients

---

Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs

Disabling client side rate limiting for GDC, real fix should come on develop.
What this means is if we're spamming the refresh button, we'll have rate limit warnings coming from the services popping up in our logs.
Real fix would be to come back to async await and simplify the error catching flow, catch the rate limit exception and only start rate limiting client side once we get that exception (instead of doing our own client side rate limit logic which isn't the same as the one applied on the server)
Real fix draft: 
https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/501
[MTT-2664](https://jira.unity3d.com/browse/MTT-2664)
[MTT-2668](https://jira.unity3d.com/browse/MTT-2668)
1. Spam refresh on lobby list
2. Try to create and quit and create …

hack fix: disabling client side rate limiting for GDC

---

Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs

(cherry picked from commit 89f99188fc4d379d15865e639bd606c57757976a)
1. ...
2. ...

cherrypick fix: Adding handling of host disconnect (#486)

---

Assets/BossRoom/VFX/Materials/FX_M_Tiling_Texture_03.mat
Assets/BossRoom/VFX/Meshes/FX_Ms_Billboard.fbx.meta
Assets/BossRoom/VFX/Meshes/FX_Ms_Ice.fbx.meta
Assets/BossRoom/VFX/Meshes/FX_Sphere.fbx
Assets/BossRoom/VFX/Meshes/FX_Sphere.fbx.meta
Assets/BossRoom/VFX/Meshes/FX_tank_shield.fbx.meta
Assets/BossRoom/VFX/Meshes/Ms_HalfSphere.FBX
Assets/BossRoom/VFX/Meshes/Ms_HalfSphere.FBX.meta
Assets/BossRoom/VFX/Prefabs/Boss/FX_Boss_Charge_Motion.prefab
Assets/BossRoom/VFX/Prefabs/Boss/FX_Boss_Charge_arrow.prefab
Assets/BossRoom/VFX/Prefabs/Shared Hero FX/FX_run_smoke.prefab

This is an optimization pass on some VFX. These were done for the memory issues that were happening on iOS, but are a good optimization to have overall. It includes reducing the amount of geometry used for the boss charge effects, as well as for the running particle effects. Reducing the complexity of these effects will mitigate there being massive tri count spikes, especially when fighting the boss with a ton of imps running around. I've also adjusted the import settings for the VFX meshes to not include unnecessary things like cameras, lights, animations, materials, etc.
Here are some images of things changed:
Boss charge arrow geometry density before vs after:
Boss charge motion effect geometry density before and after (from 7-8k tris to 2-3k tris):
And from the run smoke effect (as …

Boss and run VFX Optimizations

---

Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacterMovement.cs

Simple `IsServer` check inside `ServerCharacterMovement` to prevent client writing to `NetworkVariable` error from appearing when the application is closed.
Similar null guard on application exit (https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/516).
Fixes issue(s): [MTT-2475](https://jira.unity3d.com/browse/MTT-2475)
1. Create a build and connect to another player via lobbies
2. Close the client's app entirely when inside the game scene after character select.
3. Notice no errors from `ServerCharacterMovement` are added to player log.

fix: client writing to NetworkVariable inside ServerCharacterMovement

---

Assets/BossRoom/Scripts/Client/UI/UIQuitPanel.cs
Assets/BossRoom/Scripts/Shared/ApplicationController.cs
Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs

Removing quit when lobby detects host left.
This should already be handled by NGO side callback (on disconnect)
Adding in-editor quit, to have the same behaviour as builds
[MTT-2744](https://jira.unity3d.com/browse/MTT-2744)
1. Tested in char select scene, host quits.
2. Tested in game scene, host quits.

lobby fix: Removing quit when lobby detects host left.

---

Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs

Before sending a lobby create request, the lobby name will be populated with a default room name string.
Fixes issue(s): [MTT-2748](https://jira.unity3d.com/browse/MTT-2748)
1. Create a lobby without populating the name input field with any characters.
2. Lobby will be created and will jump to CharSelect scene.

fix: populate lobby room name if creation room input field is empty

---

Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs

Cherry pick of [522](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/522).

fix: populate lobby room name if creation room input field is empty (#522)

---

.github/workflows/leak_detect.yml

Adding leak detection action for project ID.
This depends on slack bot for sending notifications to our private project channel.
Tested in private channel adding and removing a project ID, got slack notif when project ID was detected.

chore: adding project ID leak detect

---

Assets/BossRoom/Scripts/Client/UI/PostGameUI.cs
Assets/BossRoom/Scripts/Shared/ApplicationController.cs
Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs

Fixes a bug where pressing the "return to menu" button in the post game screen did not do anything when pressing the button. A repeated (2nd) press of the button would correctly load the menu scene.
When returning to the menu from the post game scene the active lobby was not quit so the lobby list still showed 2/6 players and did not allow the client to join the lobby again.
Fixes issue(s): [MTT-2791](https://jira.unity3d.com/browse/MTT-2791)
- Build and run a host (create a lobby session)
- Run a client in editor and join the host.
- Select characters and press ready
- Use the cheat window to go to the post game lobby
- Press the "return to menu" button on the client

fix: postgame menu button

---

Assets/BossRoom/Scenes/MainMenu.unity
Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs

Cherry pick of [535](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/535).

fix: IP window button

---

Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs

UnityServicesUIHandler assumed that OriginalException is non-null - fixed that with pattern-matched check
1. ...
2. ...

Fix for clients getting nullref when lobby host disconnects

---

ProjectSettings/DynamicsManager.asset

PCs and NPCs were capable of colliding with column pieces (the Debris layer). I've adjusted the collision matrix to prevent this.
MTT-2469 - https://jira.unity3d.com/browse/MTT-2469
1. Start the game and go to the Boss's room
2. Make the Boss run into some columns - observe that the columns break, but the pieces just fall to the ground and afterwards are not interactable with the PCs and NPCs

fix: adjusted layer collision matrix 

---

Assets/BossRoom/Scenes/BossRoom/NavMesh-DungeonNavMesh.asset

This PR brings a QoL fix for navigation. The nav mesh in the game scene had floaters due to some objects not being excluded outright from the bake, as seen below:
The new bake:
Fixes issue(s): This is a QoL PR which came about from working on [MTT-2412](https://jira.unity3d.com/browse/MTT-2412).
This is a cherrypick-able fix that should be in develop as well.
A subsequent PR will actually address the issue of the Rogue being able to dash to tops of columns.
Edit: the prefabs that were modified here initially will instead be modified in the rogue dash fix PR.

fix: nav mesh floating patches removed

---

Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs
Assets/BossRoom/Scripts/Client/com.unity.multiplayer.samples.bossroom.client.asmdef
Assets/BossRoom/Scripts/Shared/ClientPrefs.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
Assets/BossRoom/Scripts/Shared/ProfileManager.cs
Assets/BossRoom/Scripts/Shared/ProfileManager.cs.meta
Assets/BossRoom/Scripts/Shared/com.unity.multiplayer.samples.bossroom.shared.asmdef
Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs

(cherry picked from commit 46e2cef6c5aa5691eee3b53ef4a1bf67e0b039a8) (#488)
1. ...
2. ...

cherrypick feat: replace guid with auth playerid for session management (#488)

---

Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs

This happens if the main menu scene switches too fast client side and we're done switching before we're actually disconnected.
This will need to be fixed for real when UTP fixes flushing transport side (MTT-2821).
Fixes issue(s): [MTT-2818](https://jira.unity3d.com/browse/MTT-2818)
Tested multiple times client and host leaving, host bring back clients to main menu, interchanging, client is now the host, leaves, brings other back to main menu.

fix: workaround for fixing the loading screen never going away on clients

---

Assets/BossRoom/Scenes/Startup.unity
Assets/BossRoom/Scripts/Shared/ApplicationController.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ClientGameNetPortal.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
Assets/BossRoom/Scripts/Shared/Net/UnityServices/Infrastructure/RateLimitCooldown.cs
Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyAPIInterface.cs
Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs

(cherry picked from commit 93ff764ec8a89302721fd2d54fc36f18ac9fb954) (#515) but without the code related to auto-reconnect
1. ...
2. ...

cherrypick fix: leaving lobby when disconnecting (#515)

---

Assets/BossRoom/Models/UI_LobbyBox_LockedIn.anim
Assets/BossRoom/Prefabs/UI/CharacterSelectCanvas.prefab
Assets/BossRoom/Prefabs/UI/PlayerSeatTemplate.prefab

I've adjusted the UI in such a way that on wide screens (21:9 was my reference resolution) the Unready button is not as overlapped by character selection thingy. I've also made the clickable zone for the character selectors smaller. Character selection animation that slides the character image upward was also made less dramatic. Overall it's much easier to hit the unready button now.
MTT-2470
1. Start the game with two clients on a wide aspect ratio
2. Select the right-most character in the character selection and hit ready. 
3. Observe that the unready button is much easier to get to now.

fix: unready button not clickable on wide screens

---

Assets/BossRoom/Scripts/Client/Game/Entity/ClientProjectileVisualization.cs
Assets/BossRoom/Scripts/Server/Game/Entity/ServerProjectileLogic.cs
Assets/BossRoom/VFX/Prefabs/Archer/fx_ArrowGraphics.prefab
Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow1Graphics.prefab
Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow2Graphics.prefab
Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow3Graphics.prefab

A ClientRpc was invoked on an arrow when it was despawned. This PR prevents that from happening.
Additionally, a quick fix has been added to reset the VFX of the arrow, specifically the TrailRenderer, when it is spawned/despawned.
Fixes issue(s): [MTT-2835](https://jira.unity3d.com/browse/MTT-2835)
Reproducing the ClientRpc error can be quite a challenge, but spamming arrows with the archer should produce consistent trails and no errors.

fix: arrow ClientRpc error

---

Assets/BossRoom/Material/Characters/Hero_Eyes_sheet.mat

A very small change but once I saw it I couldn't unsee it. Edited the material that handles the player character's eyebrows to make them darker. They match their lil icons better now. This should be in both develop and the GDC branch
Before:
After:
[Jira ticket here](https://jira.unity3d.com/browse/MTT-2762)

Fix: Darker Eyebrows for Player Characters

---

Assets/BossRoom/Prefabs/Debug Overlay Canvas.prefab
Assets/BossRoom/Scripts/Shared/Net/NetworkStats.cs

This fixes the sizing issue on the RTT text above the Client/Server type text. Text has also been converted to TMPro components.
Fixes issue(s): [MTT-2831](https://jira.unity3d.com/browse/MTT-2831)
1. Host/Join game and read text on bottom left of screen.

fix: RTT text too small

---

Assets/BossRoom/Scripts/Client/Game/Entity/ClientProjectileVisualization.cs
Assets/BossRoom/Scripts/Server/Game/Entity/ServerProjectileLogic.cs
Assets/BossRoom/VFX/Prefabs/Archer/fx_ArrowGraphics.prefab
Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow1Graphics.prefab
Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow2Graphics.prefab
Assets/BossRoom/VFX/Prefabs/Archer/fx_ChargedArrow3Graphics.prefab

Cherry pick of [557](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/557).

cherrypick fix: arrow not sending a clientrpc when despawned, vfx reset on spawn/despawn

---

Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs

This PR simply adds IsClosingClients to the condition for loading a scene offline vs online in SceneLoaderWrapper.
Fixes issue(s): [MTT-2832](https://jira.unity3d.com/browse/MTT-2832)
1. Start hosting a game
2. Return to main menu via the quit button
3. See no null refs anymore

fix: nullref on host when disconnecting

---

Assets/BossRoom/Scripts/Shared/Infrastructure/UpdateRunner.cs

Added guarding that would prevent us from having an error when adding multiple instances of the same callback to the UpdateRunner. Previously it was possible to slip in such an operation.
MTT-2838
MTT-2838
1. ...
2. ...

fix: updaterunner item already added

---

Assets/BossRoom/Models/ClickFeedbackController.controller
Assets/BossRoom/Models/ClickFeedbackController.controller.meta
Assets/BossRoom/Models/UI_GroundClick.anim
Assets/BossRoom/Models/UI_GroundClick.anim.meta
Assets/BossRoom/Prefabs/Character/PlayerAvatar.prefab
Assets/BossRoom/Prefabs/Click_Feedback.prefab
Assets/BossRoom/Scripts/Client/ClientClickFeedback.cs
Assets/BossRoom/Scripts/Client/Game/Character/ClickFeedbackLerper.cs
Assets/BossRoom/Scripts/Client/Game/Character/ClickFeedbackLerper.cs.meta
Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
Assets/BossRoom/VFX/Materials/GroundClick.mat
Assets/BossRoom/VFX/Prefabs/UI/fx_GroundClickFX.prefab

A bug fix turned refactor of the player click feedback target. Before, it was a particle system with a single plane mesh particle being scaled over life, just following the cursor's position every 20 frames. Now it is a quad with a snazzier scaling animation and interpolated following of the cursor, to create a smoother, more seamless look and feel. 
Fernando and I worked together on the interpolation, and part of the change was increasing the frequency of raycasts slightly for a smoother feel, let me know your thoughts on that for balancing performance and smoothness!
The red dot bug was seemingly an issue with the GPU dynamic instancing that particle systems use--it appeared with instancing turned on, and didn't with instancing turned off. It happened on every platform, in builds, and …

Fix: Refactor of click target feedback

---

Assets/BossRoom/Scripts/Shared/ApplicationController.cs

This PR simply adds a try/catch to LeaveBeforeQuit to make sure that we quit even if exceptions happen.
Fixes issue(s): [MTT-2656](https://jira.unity3d.com/browse/MTT-2656)
Sadly, we haven't found repro steps to MTT-2656

fix: null refs preventing users from quitting

---

Assets/BossRoom/Prefabs/CharGFX/PlayerGraphics_Mage.prefab

One of Mage's FX was offset at (0,0,50) on spawn. Resetting that offset removes the weird green FX teleportation bug.
Fixes issue(s): [MTT-2842](https://jira.unity3d.com/browse/MTT-2842)
1. Do Mage Heal and rotate around & move.

fix: mage FX graphics not offset

---

Assets/BossRoom/Scripts/Shared/ApplicationController.cs
Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyAPIInterface.cs
Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs

This is a cherrypick from (#563), with some additional cleanups
1. ...
2. ...

cherrypick fix: null refs when quitting (#563)

---

Assets/BossRoom/Scripts/Shared/ApplicationController.cs

setting to 120 so it doesn't influence RTT too much, but still shaves off about 1/3 of CPU usage when running 2 builds on the same machine
We'll need to test this on Android, make sure this doesn't mess things up. @fernando-cortez @jilfranco-unity if one of you guys could test it on your devices, that'd be great :)

fix: hard coding frame rate

---

Assets/BossRoom/Prefabs/CharGFX/PlayerGraphics_Mage.prefab

Cherry pick of [571](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/571).

cherry pick fix: mage FX graphics not offset (#571)

---

Assets/BossRoom/Scripts/Shared/ProfileManager.cs

Running BossRoom on two instances locally, either when cloning the project manually, or when using Virtual Projects. When attempting to host in one Editor and then join a game in the other Editor, we get a conflict with the message "You have logged in elsewhere using the same account." since they are both trying to join using the same user ID.
When running in the Editor and not a ParrelSync clone, make a unique ID from the Application.dataPath. This will work for cloning projects manually, or with Virtual Projects. Since only a single instance of the Editor can be open for a specific dataPath, uniqueness is ensured.

fix: Generate unique Profile ID on clone project

---

Assets/BossRoom/Scripts/Client/AnimationCallbacks/AnimatorFootstepSounds.cs
Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacterMovement.cs
Assets/BossRoom/Scripts/Shared/Game/Action/ActionBase.cs
Assets/BossRoom/Scripts/Shared/Net/NetworkStats.cs

Performance QoL improvements (all CPU-based). Many changes here involve caching local variables, and/or limiting calls out to external APIs such as Netcode when possible, which all contribute to lower GC and lower execution times. All screengrabs below were taken on the min-spec Android (Samsung J2).
`ClientCharacterVisualization` pre:
`ClientCharacterVisualization` post:
`AnimatorFootstepSounds` post:
`ServerCharacterMovement` pre:
`ServerCharacterMovement` post:
[MTT-2471](https://jira.unity3d.com/browse/MTT-2471)

fix: performance improvements (CPU-only)

---

Assets/BossRoom/Scripts/Shared/ApplicationController.cs
Assets/BossRoom/Scripts/Shared/Infrastructure/DIScope.cs
Assets/BossRoom/Scripts/Shared/Infrastructure/PubSub/MessageChannelDIExtensions.cs

Instead of trying to dynamically spawn message queues using reflection, we're now instantiating them manually in application controller. This way, they won't get stripped out by IL2CPP's code stripping (which can't be deactivated).
Another solution could have been to use ref types for messages instead of value types, since those won't get stripped in generic types. However this creates allocations each time we're sending a message internally which is no bueno.
MTT-2663

fix: fixing issue with iOS black screen where message queue constructor would get stripped out [MTT-2663]

---

Assets/BossRoom/Scripts/Server/Game/Entity/ServerProjectileLogic.cs

Without repro steps for the attached ticket, this PR should address the issue for RPCs sent from an arrow on the host. Basically, OnNetworkDespawn() never cleared a flag that prevented any FixedUpdate() logic, thus potentially sending an RPC on a despawned object. This has now been taken care of and will be extensively tested in next test session.
[[MTT](https://jira.unity3d.com/browse/MTT-3134)](https://jira.unity3d.com/browse/MTT-3134)

fix: arrow despawned rpc [MTT-3134]

---

Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyCreationUI.cs
Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyListItemUI.cs
Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
Assets/BossRoom/Scripts/Client/UI/RoomNameBox.cs
Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LocalLobby.cs

This PR removes IP/Port and OnlineMode from lobbies since direct IP flow has been moved into its own debug flow and lobbies are relay-based. A suspicion here is that old lobbies won't be able to connect to these new lobbies.
[MTT-3214](https://jira.unity3d.com/browse/MTT-3214)

chore/fix: remove online mode and IP/port from lobbies [MTT-3214]

---

Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyAPIInterface.cs
Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs
Packages/com.unity.multiplayer.samples.coop/Utilities/Net/SessionManager.cs

This is a quick PR to prevent RemovePlayerFromLobbyAsync from throwing a PlayerNotFound exception, which is something that is already handled. It also changes the error logs for when SessionManager does not find a player's session data to regular logs, since this is also already handled game-side through the null return value.
[MTT-3249](https://jira.unity3d.com/browse/MTT-3249) & [MTT-2930](https://jira.unity3d.com/browse/MTT-2930)

fix: silencing errors that are not errors [MTT-2930] [MTT-3249]

---

Assets/BossRoom/Scripts/Client/UI/HeroActionBar.cs

Input was never detected for opening emote drawer. An input check for Alpha4 has been added to `HeroActionBar` to open/close emote drawer.
[MTT-3236](https://jira.unity3d.com/browse/MTT-3236)

fix: Alpha4 input press doesn't open emote drawer on UI [MTT-3236]

---

Assets/BossRoom/Scripts/Client/UI/UIStateDisplayHandler.cs
Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacterMovement.cs

This PR resolves an issue encountered when late-joining a lobby that was already mid-game. Granted, the scenario described was never reproduced, but it likely came from a scene init race condition on spawned characters (including imps/boss) and the navigation object inside the Boss Room scene. This moves that critical `GameObject.Find` to the NetworkObject's `OnNetworkSpawn()`, when both are guaranteed to have invoked `Awake()`. It also removes an unnecessary `GameObject.Find` calculation performed on clients.
[MTT-3248](https://jira.unity3d.com/browse/MTT-3248)

fix: only server finds navigation object, asserts refactored [MTT-3248]

---

Assets/BossRoom/Scenes/MainMenu.unity
Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs

I've added the popup that tells users to set up their project id. Also adjusted the flow slightly - if there's no project id, we block away the lobby UI and prevent attempts to authenticate (they'd cause errors and nuisance popups)
MTT-3265

feat: Added popup that tells users to set up project id if it's not set up [MTT-3265][MTT-3237]

---

Assets/BossRoom/Scenes/PostGame.unity
Assets/BossRoom/Scripts/Client/UI/PostGameUI.cs
Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs
Assets/BossRoom/Scripts/Server/Game/State/ServerBossRoomState.cs
Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
Assets/BossRoom/Scripts/Shared/ApplicationController.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/ServerGameNetPortal.cs
Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs

This PR adds a parameter to decide if we load through NetworkSceneManager or SceneManager when we call SceneLoaderWrapper.
[MTT-2828](https://jira.unity3d.com/browse/MTT-2828)

fix: scene loading issue when shutting down [MTT-2828]

---

Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
Assets/BossRoom/Scripts/Shared/Net/UnityServices/Auth/AuthenticationServiceFacade.cs

Added a relogin function to the AuthenticationServiceFacade - it checks if we're no longer authenticated to do api calls and then re-signs in.
This is to prevent HTTP 401 when our token expires.
In order to prevent any potential issues when the UI was left hanging for a long time - we do a relogin attempt (which immediately bounces, if it's not needed) before any of the lobby calls from the UI. 
UI now also handles the failure to reconnect - it would unlock the UI's but would NOT do the lobby calls that require us to be authenticated. UI resets itself to try again, essentially. 
MTT-3253

fix: relogin when auth token is stale [MTT-3253]

---

Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs

This PR reverts a feature that is sometimes interpreted as a bug to reduce confusion. Now, during character select, players will no longer be set as unready when a new player joins or when one leaves during the closing of the lobby.

fix: setting players unready when one leaves or joins

---

Assets/BossRoom/Scripts/Shared/Game/GameEventMessage.cs
Assets/BossRoom/Scripts/Shared/Infrastructure/PubSub/MessageChannelDIExtensions.cs
Assets/BossRoom/Scripts/Shared/Infrastructure/PubSub/NetworkedMessageChannel.cs
Assets/BossRoom/Scripts/Shared/NetworkNameState.cs
Packages/manifest.json
Packages/packages-lock.json

Bump to pre.8
Fixing some breaking changes after bump.
[MTT-3413](https://jira.unity3d.com/browse/MTT-3413)

fix: bump to pre.8 and fix compile issues [MTT-3413]

---

Assets/BossRoom/GameData/Character/Imp/VandalImp.asset
Assets/BossRoom/GameData/Character/Imp/VandalImp.asset.meta
Assets/BossRoom/Material/Characters/Toon/Hair_Imp_Bomb.mat
Assets/BossRoom/Material/Characters/Toon/Hair_Imp_Bomb.mat.meta
Assets/BossRoom/Material/Characters/Toon/Head_Imp_Bomb.mat
Assets/BossRoom/Material/Characters/Toon/Head_Imp_Bomb.mat.meta
Assets/BossRoom/Material/Characters/Toon/Helmet_Imp.mat
Assets/BossRoom/Material/Characters/Toon/Helmet_Imp.mat.meta
Assets/BossRoom/Material/Characters/Toon/Torso_Imp_Bomb.mat
Assets/BossRoom/Material/Characters/Toon/Torso_Imp_Bomb.mat.meta
Assets/BossRoom/Material/Characters/Toon/Weapons_VandalImp.mat
Assets/BossRoom/Material/Characters/Toon/Weapons_VandalImp.mat.meta
Assets/BossRoom/Models/Animation Controllers/CharacterSetController_VandalImp.overrideController
Assets/BossRoom/Models/Animation Controllers/CharacterSetController_VandalImp.overrideController.meta
Assets/BossRoom/Models/CharacterSet.fbx
Assets/BossRoom/Prefabs/CharGFX/VandalImpGraphics.prefab
Assets/BossRoom/Prefabs/CharGFX/VandalImpGraphics.prefab.meta
Assets/BossRoom/Prefabs/Character/VandalImp.prefab
Assets/BossRoom/Prefabs/Character/VandalImp.prefab.meta
Assets/BossRoom/Prefabs/NetworkingManager.prefab
Assets/BossRoom/Textures/Characters/Boss_Torso_CLR.tga
Assets/BossRoom/Textures/Characters/Imp_Helmet_CLR.tga
Assets/BossRoom/Textures/Characters/Imp_Helmet_CLR.tga.meta
Assets/BossRoom/Textures/Characters/Imp_Weapons_CLR.tga
Assets/BossRoom/Textures/Characters/VandalImp_Head_CLR.tga
Assets/BossRoom/Textures/Characters/VandalImp_Head_CLR.tga.meta
Assets/BossRoom/Textures/Characters/VandalImp_Torso_CLR.tga
Assets/BossRoom/Textures/Characters/VandalImp_Torso_CLR.tga.meta

First import of all the vandal imp artwork--not completely implemented into gameplay yet, but pushing early to make bumping to 2021 easier. Also tinted the boss' helmet horns a bit so he wouldn't feel left out.
Here's some an image of the vandal imp!
And the slightly modified boss helmet
[Jira ticket MTT-2732 here](https://jira.unity3d.com/browse/MTT-2732)

Feat: First Import of Vandal Imp Art[ [MTT-2732]

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md

Following the process similar to what the SDK team is doing for their own changelogs
Updating PR templates with these new instructions, plus adding instructions for tests

chore: adding template instructions and updating how we update our changelogs

---

Assets/BossRoom/Scripts/Game/Client/State/ClientMainMenuState.cs

This PR simply unregisters the callback to ProfileManager.OnProfileChanged when ClientMainMenuState is destroyed.
[MTT-3585](https://jira.unity3d.com/browse/MTT-3585)

fix: unregister profile manager callback [MTT-3585]

---

Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ClientLoadingScreen.cs

This PR fixes the issue where the progress bars in the loading screen would not be properly deactivated and reactivated when a new scene load occurred after a client disconnected.
[MTT-3616](https://jira.unity3d.com/browse/MTT-3616)

fix: loading progress bars mismatch [MTT-3616]

---

Assets/BossRoom/Prefabs/UI/CharacterSelectCanvas.prefab

A tiny PR that includes edits to the collision of the character portraits in the CharSelect scene so that you can't click on them outside the edges of the portraits
Example of old collision:
Example of new collision:
[MTT-3680](https://jira.unity3d.com/browse/MTT-3680)
- [N/A] Tests have been added for boss room and/or utilities pack
- [N/A] Release notes have been added to the [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file

Fix: Char Select UI Collision [MTT-3680]

---

Assets/BossRoom/VFX/Materials/FX_M_GroundCrack_01.mat
Assets/BossRoom/VFX/Materials/FX_M_GroundCrack_02.mat
Assets/BossRoom/VFX/Materials/FX_M_ImpExplosionFire.mat
Assets/BossRoom/VFX/Materials/FX_M_Shockwave.mat
Assets/BossRoom/VFX/Materials/FX_M_SmokeDissolveMultip.mat
Assets/BossRoom/VFX/Materials/FX_M_Snowflake_Additive.mat
Assets/BossRoom/VFX/Materials/FX_M_Sparks.mat
Assets/BossRoom/VFX/Materials/FX_M_StylizeSmoke_02.mat
Assets/BossRoom/VFX/Materials/FX_M_StylizeSmoke_Falldown.mat
Assets/BossRoom/VFX/Materials/FX_M_Trail_01.mat
Assets/BossRoom/VFX/Materials/FX_M_Trail_02.mat
Assets/BossRoom/VFX/Materials/FX_M_Wave_01.mat

Fixed up some broken shader references in these materials. Spurred by noticing the broken ref on the fall down VFX that plays when a character is defeated in our last playtest. I think these got messed up in the big shader/material consolidation, but I didn't notice because they're not all used in game. It's still good to have these materials though since they're hooked into other currently unused prefabs (like the frost bolt for the mage, which could be cool to implement in the future?)
https://jira.unity3d.com/browse/MTT-3681
- [N/A] Release notes have been added to the [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file

Fix: Broken Shader References [MTT-3681]

---

Assets/BossRoom/Material/Characters/Enemy_Eyes_sheet.mat
Assets/BossRoom/Material/Characters/Enemy_Mouth_sheet.mat
Assets/BossRoom/Material/Characters/Hero_Eyes_sheet.mat
Assets/BossRoom/Material/Characters/Hero_Mouth_sheet.mat

The glowing eyes issue was introduced after bumping the URP version with the bump to 2021 LTS. It's a bug with how the Simple Lit shader that comes with the URP package handles lighting in the scene (I've raised the issue with the URP team on slack). Fix I ended up going with was to switch the eye and mouth materials for the characters and imps to use an unlit shader. 
Before:
Now:
This is a pretty small fix--should this be added to the change list? 
[MTT-3688](https://jira.unity3d.com/browse/MTT-3688)

Fix: Glowing Eyes on Low Quality Setting on Android [MTT-3688]

---

Assets/BossRoom/Scenes/PostGame.unity

A tiny PR for a fix for the broken Boss Room title in the post game scene. Noticed that there were flickering pixelated artifacts during a playtest on a Samsung s10e. Further investigation showed the title image just not showing up at all on the J2. Fix was just changing the component type from raw image to image, matching exactly how it's set up in the main menu scene. 
[MTT-3687](https://jira.unity3d.com/browse/MTT-3687)
- [N/A] Release notes have been added to the [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file

Fix: Flickering Artifacts on Boss Room Title in Post Game Scene [MTT-3687]

---

Assets/BossRoom/Scripts/Game/ConnectionManagement/ClientGameNetPortal.cs

This PR simply adds handling of IncompatibleBuildType to ClientGameNetPortal.OnDisconnectOrTimeout. It wasn't originally added to the switch-case, which led to the NotImplementedException being thrown, instead of sending a ConnectStatus message like it used to.
[MTT-3689](https://jira.unity3d.com/browse/MTT-3689)
- [n/a] Release notes have been added to the [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file

fix: no popup when incompatible build types [MTT-3689]

---

Assets/Scripts/Gameplay/UI/Lobby/LobbyJoiningUI.cs
Assets/Scripts/Gameplay/UI/Lobby/LobbyUIMediator.cs

This PR removes a redundant query for lobbies to be refreshed when the lobby UI is shown. When the UI is shown, a manual refresh is invoked, as well as a repeating query which is invoked immediately (this is the one that is throttled). Just the repeating refresh is left over.
The reason it was not reproduceable when the Joining UI was closed and reopened was because the query job was not unsubscribed when the close button on the UI was invoked. A subsequent opening of the joining UI would try to create a repeating query job which was refused, and so only the manual refresh was invoked (leading to no rate limiting).
[MTT-4018](https://jira.unity3d.com/browse/MTT-4018)

fix: removing redundant lobby refresh and unsubscribing from lobby queries [MTT-4018]

---

Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectedState.cs
Assets/Scripts/ConnectionManagement/ConnectionState/HostingState.cs

Fix to re-introduce lobby heartbeats such that lobby owners push lobby data on update intervals & non-owners receive individual lobby updates on said intervals. This resolves lobbies being destroyed on their own since data was not being pushed up to the service.
[MTT-4210](https://jira.unity3d.com/browse/MTT-4210)

fix: restoring lobby heartbeat [MTT-4210]

---

Assets/Scripts/Gameplay/Input/ClientClickFeedback.cs
Assets/Scripts/Utils/NetworkOverlay/NetworkStats.cs
CHANGELOG.md

This PR preserves the NetworkBehaviour index order between server and clients, such that indexing issues do not occur. NetworkBehaviours were being destroyed based on Owner status and so there was a mismatch on sending/receiving RPCs. Instead, NetworkBehaviours are simply disabled.
[MTT-4481](https://jira.unity3d.com/browse/MTT-4481)

fix: disabling NetworkBehaviours instead of destroying them [MTT-4481]

---

Assets/Scripts/Gameplay/GameState/ServerBossRoomState.cs

This PR changes when we register and un-register to NGO callbacks within ServerBossRoomState, making it simpler and clearer. It is now only done once in OnNetworkSpawn and undone once in OnNetworkDespawn. Before this, it relied on OnLoadComplete to register those callbacks (which happens every time any scene is loaded, including the additive scenes) and on OnUnloadeComplete to un-register them (which only happens when an additive scene is unloaded). This meant that we would register to these callbacks multiple times and we would not un-register properly afterwards.
Here are the repro steps for the bug this is fixing:
1.Start a game with a host and at least one client
2.Progress through the game up to the postgame state
3.As a client, leave the game
No addition to changelog since this bug …

fix: game frozen when client leaves in postgame [MTT-4342]

---

Assets/Prefabs/Game/PickUpPot.prefab

PickupPot lost its reference to NetworkTransform component. This caused some NRE while dropping the pot. Simply just hooking up that reference again.
Found while testing locally. No Jira as it's a trivial fix.

fix: NetworkTransform reference on PickupPot re-hooked up

---

Assets/Prefabs/NetworkingManager.prefab
CHANGELOG.md

This PR reduces the MaxPacketQueueSize UTP parameter to be 256 instead of its current 512. This slightly reduces the amount of memory needed for those queues, by around 1 MB. A higher value than this was not necessary since Boss Room only uses reliable channels for its RPCs and custom messages, and because we are limited by a maximum of 32 in-flight packets per connection anyways, it is impossible to have more than a total of 7*32=224 packets in flight in total. I put it slightly higher, at 256, to allow for internal traffic from UTP.
[MTT-4595](https://jira.unity3d.com/browse/MTT-4595)

feat: reducing MaxPacketQueueSize to 256 [MTT-4595]

---

Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectingState.cs
Assets/Scripts/ConnectionManagement/ConnectionState/ClientReconnectingState.cs

Removing warning around using an async call without an await that pops up when first starting the game. This seems the be the correct behaviour.
Renaming the method call to make sure we're aware of this if we decide to call this somewhere else.
[MTT-4658](https://jira.unity3d.com/browse/MTT-4658)
- n/a Tests have been added for boss room and/or utilities pack
- n/a Release notes have been added to the [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file

fix: fixing warnings when doing golden path [MTT-4658]

---

Assets/Prefabs/Game/ImpTossedItem.prefab
CHANGELOG.md

VandalImp tossed item only applies damage to PCs, and the damage has been increased significantly.
[MTT-4762](https://jira.unity3d.com/browse/MTT-4762)
- [ N/A] Tests have been added for boss room and/or utilities pack

fix: VandalImp tossed item only affects players and damage bumped [MTT-4762]

---

Assets/Prefabs/Dungeon/Dungeon Pieces/pots/env_pot_heavy.prefab

Fixed up a broken material reference on the LOD1 of the decorative pots
[[MTT-4750]](https://jira.unity3d.com/browse/MTT-4750)
[N/A] Tests have been added for boss room and/or utilities pack
[N/A] Release notes have been added to the [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file

Fix: Broken Material References on Decorative Pots [MTT-4750]

---

CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/CustomNetStatsMonitorConfiguration.asset
Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/CustomNetStatsMonitorConfiguration.asset.meta
Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/NetStatsMonitorPrefab.prefab

Multiple times during playtests we've wished for RTT presented as a graph instead of as a single value.
Wish no more
[MTT-4788](https://jira.unity3d.com/browse/MTT-4788)
- n/a Tests have been added for boss room and/or utilities pack

fix: adding RTT graph to RNSM [MTT-4788]

---

ProjectSettings/QualitySettings.asset

Switched the default quality setting to be medium both in builds and in editor!
N/A

Fix: Changed Default Quality Setting to Medium

---

README.md

Adding link to feedback form at the top

---

CHANGELOG.md

Updating broken PR links (shouldn't be linked to jira)

---

CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/Utilities/Net/RNSM/CustomNetStatsMonitorConfiguration.asset
Packages/manifest.json
Packages/packages-lock.json

Bumped RNSM to 1.1.0
Switched x axis units to seconds instead of frames now that it's available. This means adjusting the sample count to a lower value as well to 30 seconds, since the x axis was moving too slowly.
-  Tests have been added for boss room and/or utilities pack

feat: bumping RNSM to 1.1.0

---

Assets/Scripts/Gameplay/GameplayObjects/Character/ClientCharacter.cs
Assets/Scripts/Utils/NetworkOverlay/NetworkStats.cs
CHANGELOG.md

Quick PR to remove cached NetworkBehaviour status checks that were previously allocating memory. This has since been optimized NGO-side.
[MTT-5239](https://jira.unity3d.com/browse/MTT-5239)

chore: Removing (now) redundant cached NetworkBehaviour status

---

Assets/Scripts/ConnectionManagement/ConnectionMethod.cs
Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectedState.cs
Assets/Scripts/ConnectionManagement/ConnectionState/OnlineState.cs
CHANGELOG.md

This fixes the ClientConnectedState class having the wrong base class. It now properly inherits from OnlineState instead of the base ConnectionState. This PR also moves the k_DtlsConnType constant to the ConnectionMethod class, where it is actually used.
[MTT-5293](https://jira.unity3d.com/browse/MTT-5293)

fix: wrong base class for ClientConnectedState [MTT-5293]

---

Assets/Prefabs/UI/IPPopup.prefab
Assets/Scripts/Gameplay/UI/IPHostingUI.cs
Assets/Scripts/Gameplay/UI/IPJoiningUI.cs
Assets/Scripts/Gameplay/UI/IPUIMediator.cs
CHANGELOG.md

This PR improves how we sanitize inputs when entering IP addresses and ports. Our sanitization now prevents all invalid characters when writing in those fields, and deactivates the Join/Host button when the input cannot be parsed into a NetworkEndpoint by UnityTransport.
[MTT-5894](https://jira.unity3d.com/browse/MTT-5894)

fix: better input sanitization [MTT-5894]

---

Assets/Scripts/Gameplay/Action/ActionID.cs
Assets/Scripts/Gameplay/GameState/NetworkCharSelection.cs
Assets/Scripts/Infrastructure/NetworkGuid.cs
CHANGELOG.md
README.md

`INetworkSerializeByMemcpy` interface is recommended usage for network messages containing value types. It for allows some bandwidth optimization techniques (byte packing) that are otherwise unavailable.
It is not recommended in places where object types are serialized, nor when FixedStrings are used.
`INetworkSerializeByMemcpy` [when used with FixedStrings] struct is not recommended because it will lose the bandwidth optimization - an empty FixedString128Bytes serialized normally or through `INetworkSerializable` will use 4 bytes of bandwidth, but inside an `INetworkSerializeByMemcpy`, that same empty value would consume 132 bytes of bandwidth.
[MTT-5912](https://jira.unity3d.com/browse/MTT-5912)

fix: Adding INetworkSerializeByMemcpy where recommended for network serialization [MTT-5912]

---

Assets/Scripts/Infrastructure/NetworkObjectPool.cs
CHANGELOG.md

This PR replaces our custom pool implementation using queues with the `ObjectPool` collection. It also removes the methods `InitializePool` and `ClearPool` and moves their content in `OnNetworkSpawn` and `OnNetworkDespawn`
[MTT-6263](https://jira.unity3d.com/browse/MTT-6263) & [MTT-4696](https://jira.unity3d.com/browse/MTT-4696)

refactor: replacing custom pool implementation with ObjectPool [MTT-6263]

---

Assets/Scripts/Gameplay/GameState/ClientMainMenuState.cs
Assets/Scripts/Gameplay/UI/UIProfileSelector.cs
Assets/Scripts/UnityServices/Auth/AuthenticationServiceFacade.cs
Assets/Scripts/Utils/ProfileManager.cs
CHANGELOG.md

This PR updates our profile name generation in anticipation of Authentication service's new profile name length requirements.
[MTT-6241](https://jira.unity3d.com/browse/MTT-6241)

feat: profile name authentication truncating [MTT-6241]

---

Assets/Scripts/ConnectionManagement/ConnectionState/ClientConnectingState.cs
Assets/Scripts/ConnectionManagement/ConnectionState/HostingState.cs
Assets/Tests/Runtime/ConnectionManagementTests.cs
CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/SceneLoaderWrapper.cs

This PR removes SceneLoaderWrapper.AddOnSceneEventCallback and replaces it with registrations to NetworkManager OnServerStarted and OnClientStarted callbacks.
[MTT-6242](https://jira.unity3d.com/browse/MTT-6242)

fix: decoupling SceneLoaderWrapper and ConnectionStates [MTT-6242]

---

Assets/DefaultNetworkPrefabs.asset
Assets/DefaultNetworkPrefabs.asset.meta

deleted the default network prefabs asset that I accidentally pushed
- [n/a] Release notes have been added to the [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file
- [n/a] JIRA ticket ID is in the PR title or at least one commit message
- [n/a] Include the ticket ID number within the body message of the PR to create a hyperlink

deleted default network prefabs asset

---

Assets/Scripts/UnityServices/Sessions/MultiplayerServicesFacade.cs
CHANGELOG.md

Fixing a small error logged when a client is removed from a Session.
[MTT-1161](https://jira.unity3d.com/browse/MTTB-1161)
- [ N/A ] An Index entry has been added in readme.md if applicable

fix: NullReferenceException caused when unsubscribing on session removal [MTTB-1161]

---

CHANGELOG.md
Packages/manifest.json
Packages/packages-lock.json
README.md

Upgrade transport package to 2.5.1 to profit from fixes and fix banner in README (updating its version numbers).
https://jira.unity3d.com/browse/MTT-11838

[MTT-11838] Fix: upgrade unity transport to 2.5.1 and update banner in README.md

---

Assets/Scripts/ConnectionManagement/ConnectionManager.cs
Assets/Scripts/Gameplay/GameState/ServerBossRoomState.cs
Assets/Scripts/Gameplay/GameState/ServerCharSelectState.cs
Assets/Scripts/Infrastructure/PubSub/NetworkedMessageChannel.cs
CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/LoadingProgressManager.cs
Packages/com.unity.multiplayer.samples.coop/Utilities/SceneManagement/ServerAdditiveSceneLoader.cs

This PR upgrades the project to use the OnConnectionEvent callback from Netcode for GameObjects, in favour over the unrecommended OnClientConnected/OnClientDisconnected callbacks.
This PR also removes an unnecessary Despawn invocation on a NetworkObject that is already marked to despawn with owner.
[MTTB-1147](https://jira.unity3d.com/browse/MTTB-1147)
- [ N/A ] An Index entry has been added in readme.md if applicable

feat: OnConnectionEvent callback usage in project and Utilities package [MTTB-1147]

---

Assets/Scripts/Gameplay/GameState/ClientMainMenuState.cs
Assets/Scripts/UnityServices/Sessions/LocalSession.cs
Assets/Scripts/UnityServices/Sessions/MultiplayerServicesFacade.cs

This PR provides a fix for an error raised when changing profiles. The current LocalSessionUser needed to be added to the local session before attempting to remove when reseting a session. It has since been added to the initial login flow and whenever a profile is changed by the user.
[MTT-11948](https://jira.unity3d.com/browse/MTT-11948)
- [ N/A ] Release notes have been added to the [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file
- [ N/A ] An Index entry has been added in readme.md if applicable

fix: resetting local user on profile change [MTT-11948]

---

Documentation/Unity-Relay/README.md
README.md

Quick PR to update Readme and cleanup a deprecated docs page.
N/A
- [ N/A ] Release notes have been added to the [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file
- [ N/A ] Pull request has a meaningful description of its purpose
- [ N/A ] JIRA ticket ID is in the PR title or at least one commit message

chore: readme + doc cleanup

---

Assets/Scripts/Gameplay/Configuration/NameGenerationData.cs
CHANGELOG.md

Small PR to fix the bounds issue inside of the player name generation, where the last item in the arrays for first and last nam weren't being used.
[Issue 912](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/issues/912)

fix: name generation bounds fixed to include last item
