.github/CODEOWNERS

Designating Sam as global codeowner.

adding initial codeowners file (sam as global)

---

third-party contributors.md

A file containing details on our third-party contributors.

Create third-party contributions file

---

Assets/BossRoom/Prefabs/UI/PopupPanel.prefab
Assets/BossRoom/Scenes/BossRoom.unity
Assets/BossRoom/Scripts/Client/UI/MainMenuUI.cs
Assets/BossRoom/Textures/UI/ui_dropdown_arrow.png
Assets/BossRoom/Textures/UI/ui_dropdown_arrow.png.meta
Assets/BossRoom/Textures/UI/ui_help_attack.png

Adds Action Key labels and Zoom info to help panel
New drop down arrow graphic and text in PopupPanel

Addresses Help and UI fixes from GOMPS-362

---

Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs

We landed with a compiler error after the recent merges. This fixes that.

hotfix for a compilation issue

---

Assets/BossRoom/VFX/Shaders/Prewarming.shadervariants

This is an update for a "prewarming" shadervariant change. It should remove some blue "shader loading" streaks that are visible in editor.

updating shader variants

---

Packages/manifest.json
Packages/packages-lock.json
ProjectSettings/ProjectVersion.txt

Boss Room updated to LTS v2020.3.6f1.

updating project to Unity LTS 2020.3.6f1

---

ProjectSettings/ProjectVersion.txt

Upgrading to newest LTS. No package dependencies were modified.

upgrading to 2020.3.8f1 LTS

---

Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md

Adding changelog for 0.2.0. Based on GOMPS issues with the fix version 0.2.0.
For a list of tickets per release notes entry, you can also check the [Doc PR](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/193/files#diff-faa9308cdf0b0e26b4c75d319f3cbebdcd45fa85707645adb102c707e6517456). 
Any changes entered/requested in this Samples PR I will make in the doc PR.
Requested review from a few folks, please provide feedback if you have time/info. I can update the release date to match the release branch cut.
Thanks! 🚀

docs: 0.2.0 Changelog

---

Packages/manifest.json
Packages/packages-lock.json

Boss Room latest is broken right now and the lobby doesn't work anymore.
We'll need to investigate what happened there, reverting to github version for now until we know more

Fixing parameter exception when connecting to lobby

---

Packages/packages-lock.json

MLAPI update. Necessary for new feature tasks.

updating MLAPI develop version

---

Assets/BossRoom/Scenes/BossRoom.unity

This PR fixes a bug involving the NetworkObjectPool's GlobalObjectIdHash
The prefab was removed and added back to the scene. This was caused by [an issue](https://jira.unity3d.com/browse/MTT-1688) from the sdk side with the generation of GlobalObjectIdHash for newly added network prefabs.
1. Create a build
2. Start playing with build as host and in-editor as client
3. Scene should load correctly and be playable
Should we merge this, or wait for a fix on sdk-side? I'm not sure an eventual fix on sdk-side preventing the different GlobalObjectIdHash values from occuring would fix this issue which is a result of that other issue.

fix: bug with network object pool global object id hash

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Replaces references to MLAPI to Netcode for GameObjects.
1. ...
2. ...

fix: replace mlapi references with ngo

---

Assets/BossRoom/Prefabs/UI/CharSel_Background.prefab
Assets/BossRoom/Scenes/CharSelect.unity
Assets/BossRoom/Scenes/MainMenu.unity

Updated char select background prefab to have the scene lights and reflection probe in it, that way all of the lighting and the look of the main menu, char select, and post game scenes using the prefab look the same
Before:
After:
This also edited the look of the main menu and char select screens a little bit, but I think the extra light and reflection looks nicer :)
Before:
After:
Before:
After:

Updated char select background prefab

---

Packages/manifest.json
Packages/packages-lock.json

This PR updates the version of the IET package in the manifest to the latest version.
Fixes issue(s): [MTT-1856](https://jira.unity3d.com/browse/MTT-1856) #421 
1. ...
2. ...

fix: Update IET package version to 2.1.1

---

Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs
Assets/BossRoom/Scripts/Client/Game/Entity/ClientProjectileVisualization.cs
Assets/BossRoom/Scripts/Client/Game/Utils/VisualUtils.cs
Assets/BossRoom/Scripts/Client/UI/UIStateDisplayHandler.cs

This PR fixes host-side jitter by re-enabling positional smoothing on the graphics GameObject for a player. Host-side, a player's NetworkTransform is moved on FixedUpdate. All clients, including the host, will experience their graphics GameObject be smoothly lerped to the NetworkTransform's position on Update. The camera tracking the graphics GameObject will then be consistent on host and clients.
The max rotation speed has been increased. This felt like a good compromise between an instantaneous rotation that is currently experienced and the smoothing we previously had.
Fixes issue(s): [MTT-1689](https://jira.unity3d.com/browse/MTT-1689)
1. ...
2. ...

fix: re-enabling positional smoothing on graphics GameObject

---

Assets/BossRoom/Prefabs/UI/CharacterSelectCanvas.prefab
Assets/BossRoom/Scripts/Client/UI/RoomNameBox.cs

Added button to copy room name to clipboard in character selection, on host side.
Fixes issue(s): [MTT-1988](https://jira.unity3d.com/browse/MTT-1988)
1. ...
2. ...

feat: button to copy room name to clipboard

---

Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs

This PR fixes an issue with the initialization of the SessionManager's Host data. The issue was that when initializing the data, the NetworkManager's `LocalClientId` was used, however, since it was done before the actual host started, this value was either not defined yet (0, which works) or the previous value, meaning that if a client was running earlier, their old `LocalClientId` would then be used. 
We should now have the proper value.
Fixes issue(s): [MTT-2010](https://jira.unity3d.com/browse/MTT-2010)
1. Start game session with a host
2. Join as a client
3. Leave the character selection scene as the client, then start hosting a new game session without exiting the game
4. You should be able to select a character. Before this fix, you would get an error here.

 fix: session manager host data initialization order

---

Assets/BossRoom/Scenes/PostGame.unity

This PR fixes the soft sync issue seen on clients when unloading Boss Room scene and loading PostGame scene when a host quits or when the game is lost/won (or hits debug key Q).
A malformed GlobalObjectIdHash on the PostGameState prefab instance was the cause. A new instance has been dropped into the scene.
Fixes issue(s): [MTT-2159](https://jira.unity3d.com/browse/MTT-2159)
1. Host a game and have a client join the hosted game.
2. Proceed into the BossRoom scene after selecting characters.
3. Finish a session (ie. defeating Boss, having all players faint, or by pressing debug key Q as the host).
4. Notice that clients won't log 3 GlobalObjectIdHash-related Netcode errors.

fix: soft sync error when loading PostGame scene on client

---

Assets/BossRoom/Models/Animation Controllers/CharacterSetController.controller

This PR adds a transition between the `Action - Boss Trample` and the `Trample Stop` states in the animation controller, which allows the cancellation of the `Trample` action to bring the boss back to the idle animation if the `Trample Stop` trigger is received before the `Trampling` state has started.
Fixes issue(s): [MTT-2016](https://jira.unity3d.com/browse/MTT-2016)
1. Reach the boss with a rogue while invisible
2. Use invisibility skill while near the boss (while already invisible)
3. The boss will initiate the trampling action when the player becomes visible, then cancel it when the player returns to invisibility
This might require a few tries to make it work, as sometimes the boss will use its normal attack instead.

fix: boss stuck in trampling animation when player becomes invisible during windup

---

Assets/BossRoom/Scripts/Shared/ClientPrefs.cs

This PR simply reduces the default master volume's value.
Fixes issue(s): [MTT-1993](https://jira.unity3d.com/browse/MTT-1993)
1. In the editor, click on `Edit->Clear All PlayerPrefs` to clear previous volume settings
2. Start the game
~~The music still feels a bit loud in comparison to the rest. Should we also reduce the default value for music? Or should we modify the value directly on the AudioSource component that plays the music?~~

fix: default sound too high

---

Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
Assets/BossRoom/Scripts/Server/Game/Entity/ServerBreakableLogic.cs

Quick fix to clamp hitpoint depletion when receiving damage/heal. This was observed in PR [447](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/447) where characters were damaged and HP fell below the range of [0, maxHealth], causing some UI-based inconsistencies for when to display healthbars.
Now, hitpoints for any health state can only exist within said range.
[447](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/447)
1. Test out [447](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/447) and manually kill a player multiple times through a cheat. Every other occurrence will result in the health bar displayed while a character is still fainted.
2. Manually modify the player's health …

fix: hitpoint depletion inconsistency with clamped values

---

Assets/BossRoom/Scripts/DebugCheats/DebugCheatsManager.cs

This PR adds a verification that one of the four touches is in the TouchPhase.Began phase before toggling the cheat window on mobile, so that it only toggles once.
Fixes issue(s): [MTT-2279](https://jira.unity3d.com/browse/MTT-2279)
1. Build the game on a mobile platform (tested on Android), with a dev build
2. Progress to the BossRoom scene
3. Use four fingers simultaneously touching the screen to open/close the window
4. See that it only does so once

fix: cheat window toggling on mobile

---

Assets/BossRoom/Prefabs/Dungeon/TransitionArea.prefab

Deleted a pot that was overlapping with a torch in the transition area prefab
Before:
After:

Deleted an overlapping object

---

Assets/BossRoom/Scripts/Server/Game/Action/TrampleAction.cs
Assets/BossRoom/Scripts/Server/Game/Character/ServerCharacter.cs
Assets/BossRoom/Scripts/Server/Game/Entity/DamageReceiver.cs

This PR fixes the mentioned issue by making the `TrampleAction` inflict damage through the character's `DamageReceiver` instead of directly through `ServerCharacter`, and by adding a verification for the `IsDamageable` condition before invoking the `damageReceived` event on the `DamageReceiver`.
Fixes issue(s): [MTT-2474](https://jira.unity3d.com/browse/MTT-2474)
1. Start a game with a host and at least one client
2. Have one player faint
3. Aggro the boss with another player and trigger its trample action towards the fainted player
To make testing easier, use the cheat window to toggle god mode for one player and to spawn a boss in the first room.

fix: react anim on trample attack while fainted

---

Assets/BossRoom/Scripts/Client/Game/State/ClientCharSelectState.cs
Assets/BossRoom/Scripts/Server/Game/State/ServerCharSelectState.cs
Assets/BossRoom/Scripts/Shared/Game/State/CharSelectData.cs
Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/SessionPlayerData.cs

This is a cherrypick of changes from PR #490 that were merged to the GDC branch
1. ...
2. ...

cherrypick fix: same player number for multiple players in second playthrough

---

Assets/BossRoom/Scripts/Shared/Net/ConnectionManagement/GameNetPortal.cs

Should be handed by QoS in develop. Didn't want to add new feature in a stabilization branch, adding hardcoded region instead.
[MTT-2690](https://jira.unity3d.com/browse/MTT-2690)
1. tested with us-east region, noticed lower RTT than central.
2. tested with us-west region, noticed higher RTT than central.

hack: hard code relay region

---

Assets/BossRoom/Prefabs/UI/IPPopup.prefab
Assets/BossRoom/Prefabs/UI/IPPopup.prefab.meta
Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
Assets/BossRoom/Scenes/MainMenu.unity
Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
Assets/BossRoom/Scripts/Client/UI/IPHostingUI.cs
Assets/BossRoom/Scripts/Client/UI/IPHostingUI.cs.meta
Assets/BossRoom/Scripts/Client/UI/IPJoiningUI.cs
Assets/BossRoom/Scripts/Client/UI/IPJoiningUI.cs.meta
Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs
Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs.meta
Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyCreationUI.cs
Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs

Cherry pick of [502](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/502).

feat: IP connection window inside main menu (#502)

---

Assets/BossRoom/Prefabs/UI/IPPopup.prefab
Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
Assets/BossRoom/Scenes/MainMenu.unity
Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs
Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs

A bit of a facelift for the lobby UI--mainly moving things around, adding color to the scroll bar, adding some graphics, and adding borders to the tabs to make them more like radio buttons
New Look:
Old Look:
Jira ticket [here](https://jira.unity3d.com/browse/MTT-2735)

Lobby UI Visual Rework

---

Assets/BossRoom/VFX/Materials/FX_M_Tiling_Texture_03.mat
Assets/BossRoom/VFX/Meshes/FX_Ms_Billboard.fbx.meta
Assets/BossRoom/VFX/Meshes/FX_Ms_Ice.fbx.meta
Assets/BossRoom/VFX/Meshes/FX_Sphere.fbx
Assets/BossRoom/VFX/Meshes/FX_Sphere.fbx.meta
Assets/BossRoom/VFX/Meshes/FX_tank_shield.fbx.meta
Assets/BossRoom/VFX/Meshes/Ms_HalfSphere.FBX
Assets/BossRoom/VFX/Meshes/Ms_HalfSphere.FBX.meta
Assets/BossRoom/VFX/Prefabs/Boss/FX_Boss_Charge_Motion.prefab
Assets/BossRoom/VFX/Prefabs/Boss/FX_Boss_Charge_arrow.prefab
Assets/BossRoom/VFX/Prefabs/Shared Hero FX/FX_run_smoke.prefab

Cherrypick PR for [VFX Optimizations PR](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/514) for GDC branch

Cherrypick: VFX Optimizations

---

Assets/BossRoom/Prefabs/Dungeon/BossRoom.prefab
Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor6.prefab
Assets/BossRoom/Prefabs/Dungeon/Entrance.prefab
Assets/BossRoom/Scenes/BossRoom/LightingData.asset
Assets/BossRoom/Scenes/BossRoom/Lightmap-0_comp_light.exr
Assets/BossRoom/Scenes/BossRoom/Lightmap-1_comp_light.exr
Assets/BossRoom/Scenes/BossRoom/Lightmap-2_comp_light.exr
Assets/BossRoom/Scenes/BossRoom/Lightmap-3_comp_light.exr
Assets/BossRoom/Scenes/BossRoom/Lightmap-4_comp_light.exr
Assets/BossRoom/Scenes/BossRoom/Lightmap-5_comp_light.exr
Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-0.png
Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-1.png
Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-2.png

Filled in some holes in the floor and rebaked lighting. Should be in both develop and GDC branches. Marking urgent since there really shouldn't be holes in our floors 😬 
Before:
After:
Before:
After:
Before:
After:

Fix: Holes in Floor

---

Assets/BossRoom/Prefabs/UI/IPPopup.prefab
Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
Assets/BossRoom/Scenes/MainMenu.unity
Assets/BossRoom/Textures/UI/ui_char_select_title2.png
Assets/BossRoom/Textures/UI/ui_char_select_title2.png.meta

Edited the blue graphic behind "join an existing lobby..." and "create a new lobby..." to be one image instead of two to fix a scaling issue at different aspect ratios. This fix should be on develop and the GDC branches
Before:
After:

Fix: Lobby UI Blue Banner Scaling

---

Assets/BossRoom/Scripts/Server/Game/Character/ServerAnimationHandler.cs

(cherry picked from commit 8a9ef3afaa5000cd71559167efc4fc041bcd4dc2) (#512)
1. ...
2. ...

cherrypick fix: NetworkAnimator being called on clients (#512)

---

Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs

(cherry picked from commit 0daecd7c8011d337212f9e59ff4a4eb3e0c5c5f3) (#499)
1. ...
2. ...

cherrypick fix: username changing before game (#499)

---

Assets/BossRoom/Scripts/Shared/Game/UI/Editor/NetworkLatencyWarning.cs

(cherry picked from commit 057bad5cf5085c256996cd52ec9a2429b65b4b74) (#516)
1. ...
2. ...

cherrypick fix: NREs when trying to quit (#516)

---

Assets/BossRoom/Prefabs/Dungeon/BossRoom.prefab
Assets/BossRoom/Prefabs/Dungeon/Dungeon Pieces/env_floor6.prefab
Assets/BossRoom/Prefabs/Dungeon/Entrance.prefab
Assets/BossRoom/Scenes/BossRoom/LightingData.asset
Assets/BossRoom/Scenes/BossRoom/Lightmap-0_comp_light.exr
Assets/BossRoom/Scenes/BossRoom/Lightmap-1_comp_light.exr
Assets/BossRoom/Scenes/BossRoom/Lightmap-2_comp_light.exr
Assets/BossRoom/Scenes/BossRoom/Lightmap-3_comp_light.exr
Assets/BossRoom/Scenes/BossRoom/Lightmap-4_comp_light.exr
Assets/BossRoom/Scenes/BossRoom/Lightmap-5_comp_light.exr
Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-0.png
Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-1.png
Assets/BossRoom/Scenes/BossRoom/ReflectionProbe-2.png

Cherry pick of [this PR ](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/527)for the GDC branch

Cherrypick: Fill in Floor Holes

---

Assets/BossRoom/Scenes/MainMenu.unity
Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs

Added a "Direct IP" button directly to main menu. This now lets users know how to connect via IP.
Fixes issue(s): [MTT](https://jira.unity3d.com/browse/MTT-2767).

fix: added IP button to main menu

---

Assets/BossRoom/Prefabs/UI/IPPopup.prefab
Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
Assets/BossRoom/Scenes/MainMenu.unity
Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs
Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
Assets/BossRoom/Textures/UI/ui_bg_gradient2.png
Assets/BossRoom/Textures/UI/ui_bg_gradient2.png.meta
Assets/BossRoom/Textures/UI/ui_blurred_square.png
Assets/BossRoom/Textures/UI/ui_blurred_square.png.meta

This PR includes further work on the Lobby UI, specifically the tabs. The goal of these changes is to make the UI more intuitive after receiving feedback during a playtest that the tabs still looked too much like buttons, rather than tabs
Some pictures! :)
Lobby list before:
Lobby list after:
Lobby creation before:
Lobby creation after:
IP join before:
IP join after:
IP host before:
IP host after:
[Jira ticket here](https://jira.unity3d.com/browse/MTT-2801)

Fix: More Lobby Visual Work

---

Assets/BossRoom/Prefabs/UI/IPPopup.prefab
Assets/BossRoom/Prefabs/UI/LobbyUI.prefab
Assets/BossRoom/Scenes/MainMenu.unity
Assets/BossRoom/Scripts/Client/UI/IPUIMediator.cs
Assets/BossRoom/Scripts/Client/UI/Lobby/LobbyUIMediator.cs
Assets/BossRoom/Textures/UI/ui_bg_gradient2.png
Assets/BossRoom/Textures/UI/ui_bg_gradient2.png.meta
Assets/BossRoom/Textures/UI/ui_blurred_square.png
Assets/BossRoom/Textures/UI/ui_blurred_square.png.meta

Cherrypick PR for the [Lobby UI Visual Rework PR](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/544) for the GDC branch

Cherrypick: More Lobby UI Visual Work

---

Assets/BossRoom/Scenes/BossRoom/NavMesh-DungeonNavMesh.asset

Cherry pick of [542](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/542).

fix: nav mesh floating patches removed (#542)

---

Assets/BossRoom/Prefabs/Debug Overlay Canvas.prefab
Assets/BossRoom/Scripts/Shared/Net/NetworkStats.cs

Cherry pick of [559](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/559).

cherrypick fix: RTT text too small

---

Assets/BossRoom/Material/Characters/Hero_Eyes_sheet.mat

Cherry pick PR for the [Darker Eyebrows PR](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/555) for the GDC branch

Darker Eyebrows for Player Characters (#555)

---

Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs

cherrypick feat: display popup when failing to connect to full lobby (#525)

---

Assets/BossRoom/Scripts/Client/UI/UnityServicesUIHandler.cs
Assets/BossRoom/Scripts/Shared/Net/UnityServices/Lobbies/LobbyServiceFacade.cs

This PR changes how lobby exceptions are handled. Only some of them will be shown to players through popups.
1. ...
2. ...

feat: better lobby exceptions handling

---

Assets/BossRoom/Models/ClickFeedbackController.controller
Assets/BossRoom/Models/ClickFeedbackController.controller.meta
Assets/BossRoom/Models/UI_GroundClick.anim
Assets/BossRoom/Models/UI_GroundClick.anim.meta
Assets/BossRoom/Prefabs/Character/PlayerAvatar.prefab
Assets/BossRoom/Prefabs/Click_Feedback.prefab
Assets/BossRoom/Scripts/Client/ClientClickFeedback.cs
Assets/BossRoom/Scripts/Client/Game/Character/ClickFeedbackLerper.cs
Assets/BossRoom/Scripts/Client/Game/Character/ClickFeedbackLerper.cs.meta
Assets/BossRoom/Scripts/Client/Game/Character/ClientInputSender.cs
Assets/BossRoom/VFX/Materials/GroundClick.mat
Assets/BossRoom/VFX/Prefabs/UI/fx_GroundClickFX.prefab

Cherrypick PR for [Click Feedback PR](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/569) for GDC branch

Cherrypick: Refactor of click feedback target

---

Assets/BossRoom/Prefabs/Shadow.prefab

Some tiny changes to the character shadow, just swapping the mesh from a plane to a quad and turning off collision and shadow casting
This was literally a 30 second change so no jira ticket :P

Fix: Character Shadow Simplification

---

Assets/BossRoom/Scripts/Shared/ApplicationController.cs

This PR fixes a typo in code that prevented the LeaveBeforeQuit coroutine to be called when needed.
[MTT-3127](https://jira.unity3d.com/browse/MTT-3127)

fix: alt-f4 not working while in lobby [MTT-3127]

---

Packages/com.unity.multiplayer.samples.coop/package.json
Packages/packages-lock.json

Cleanup for dependencies and bumping version
[MTT-3250](https://jira.unity3d.com/browse/MTT-3250)

bumping version and cleaning up dependencies for MTT-3250

---

.github/workflows/leak_detect.yml

Adding @here in slack message for leak detection

chore: Adding @here in slack message for leak detection

---

Assets/Readme.asset
README.md

This PR simply adds info to our two readmes (GitHub and in-project) with details on how to integrate UGS into your project.
[MTT-3263](https://jira.unity3d.com/browse/MTT-3263)

fix: add Unity Gaming Services info to readmes [MTT-3263]

---

Packages/manifest.json
Packages/packages-lock.json

feat: bump tools version for perf improvements

---

Assets/BossRoom/Scripts/Client/Game/State/ClientMainMenuState.cs
Assets/Readme.asset

CloudProjectID is now checked using `Application.cloudProjectID` instead of UnityEditor-based option.
Removed duplicate lines in our readme and also adjusted the wording in the popup.

fix: readme and projectID-monitoring popup tweaks

---

ProjectSettings/ProjectSettings.asset
RepoUtilities/InstallHooks.bat
RepoUtilities/InstallHooks.sh
RepoUtilities/pre-commit.py
RepoUtilities/pre-commit.toInstall

Adding pre-commit hooks to help keep bad things away. These will fail your commits if you're trying to include project IDs or black listed packages.
To install those, run the install script from the RepoUtilities folder.
Not tested on Windows yet.
[MTT-3302](https://jira.unity3d.com/browse/MTT-3302)

chore: adding optional pre-commit hooks [MTT-3302]

---

Packages/manifest.json
Packages/packages-lock.json

Removing experimental QoS and waiting for GA version.
QoS has a few unfixable bugs in its current state, which will be solved by upcoming 1.0.0. Waiting until then to include it.

chore: removing QoS

---

README.md

Updating readme to promote Utilities package more.

Update README.md with Utilities package ref

---

Packages/com.unity.multiplayer.samples.coop/Utilities/Testing/com.unity.multiplayer.samples.utilities.testing.asmdef

Quick constraint fix on the built-in package test asmdef to unblock builds.
No ticket numbers created. Just a quick fix.

fix: testing package constraint addition to unblock builds

---

Packages/manifest.json
Packages/packages-lock.json

chore: bump NGO to pre.9

---

Assets/BossRoom/Material/Characters/Toon/Hair_Rogue_Boy.mat
Assets/BossRoom/Material/Characters/Toon/Hair_Rogue_Girl.mat
Assets/BossRoom/Material/Characters/Toon/Head_Rogue_Boy.mat
Assets/BossRoom/Material/Characters/Toon/Torso_Imp.mat
Assets/BossRoom/Material/Characters/Toon/Torso_Rogue.mat
Assets/BossRoom/Material/Characters/Toon/Weapons_Imp.mat
Assets/BossRoom/Material/Characters/Toon/Weapons_Rogue.mat
Assets/BossRoom/VFX/Materials/FX_M_StylizeSmoke.mat
ProjectSettings/EditorSettings.asset

Quick PR to fix some annoying things.
Reserializing some mat files
Adding default namespace when creating new scripts (setting in editor settings)

Fixing 2021 new serialization and adding default namespace to editor settings

---

Assets/BossRoom/Scripts/Game/Client/UI/Lobby/LobbyJoiningUI.cs

This PR fixes that issue by having LobbyJoiningUI subscribe to the UpdateRunner to refresh its list of lobbies only when it is shown, and unsubscribe when it is hidden.
[MTT-3581](https://jira.unity3d.com/browse/MTT-3581)

fix: auth signin error on startup [MTT-3581]

---

Documentation/Images/3Players.png
Documentation/Images/Boss.png
Documentation/Images/Players.png
README.md

Updated the images in the readme since they were pre URP port :)
These are the new images!

Docs: Readme Image Updates [Skip CI]

---

CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md

This PR takes the fixes that were made for the release changelog and updates the changelog files with it.

chore: update changelogs with fixes made to the release changelog

---

Assets/Scenes/BossRoom/DungeonBossRoom.unity
Assets/Scenes/BossRoom/DungeonEntrance.unity
Assets/Scenes/BossRoom/DungeonTransition.unity

Subscenes of the Boss Room scene didn't have their contexts correctly set up - fixed that by hooking them to their ServerBossRoomState context.

fix: VContainer injection issue

---

README.md

Removing dead link to docs website

Removing dead link to docs website

---

Assets/VFX/Prefabs/Caster/FX_caster_skill_2.prefab
Assets/VFX/Prefabs/Imp/FX_IMP_attack_1_Slash.prefab
Assets/VFX/Prefabs/Imp/TossAttack/FX_IMP_TossAttack_Sparks.prefab
Assets/VFX/Prefabs/Rogue/FX_RogueSkill2_end.prefab
Assets/VFX/Prefabs/Rogue/FX_Rogue_attack_1_Slash.prefab
Assets/VFX/Prefabs/Shared Hero FX/FX_Ice_Pieces.prefab

A quick pass on our VFX to delete any unneeded animator components
- [N/A] JIRA ticket ID is in the PR title or at least one commit message
- [N/A] Include the ticket ID number within the body message of the PR to create a hyperlink

Fix: Deleting Unneeded Animators

---

Assets/Scripts/Editor/SceneBootstrapper.cs
CHANGELOG.md

Scene Bootstrapper: future proofing bootstrap scene so we don't rely on Startup's path.
With this, users that used to have the old path can now still benefit from the bootstrapper.
MTT-3707

Fix: bootstrap scene fix (MTT-3707)

---

Assets/Prefabs/UI/IPPopup.prefab
CHANGELOG.md

Adding instructions for setting host listen IP.
See screenshots
[MTT-4617](https://jira.unity3d.com/browse/MTT-4617)
- na Tests have been added for boss room and/or utilities pack

fix: better instructions for hosting ip [MTT-4617]

---

Assets/Prefabs/UI/LobbyUI.prefab
Assets/Scripts/Gameplay/UI/Lobby/LobbyJoiningUI.cs
CHANGELOG.md

This PR solves this issue by making the join button not interactable if the join code input text box is empty.
[MTT-4760](https://jira.unity3d.com/browse/MTT-4760)

fix: argument null exception when clicking the lobby join button without a join code entered [MTT-4760]

---

Assets/Readme.asset
README.md

Updating readme with Typeform for feedback. Adding to the TOC and placement of form at the end of readme. Might cause visibility issues due to placement. Open to suggestions.

Updating readme with Typeform for feedback

---

CHANGELOG.md
ProjectSettings/ProjectSettings.asset

After 2.0.0 decision, bumping versions

Version bumps

---

CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md

This updates the changelogs for the release.

Chore: update changelogs for release

---

Assets/Readme.asset

Quick replacing words in readme
[MTT-5003](https://jira.unity3d.com/browse/MTT-5003)
- n/a Tests have been added for boss room and/or utilities pack
- n/a Release notes have been added to the [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file
- n/a All commits are accompanied by meaningful commit messages
- n/a An Index entry has been added in readme.md if applicable

chore: replacing "template" for "sample" [MTT-5003]

---

CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/ClientNetworkAnimator.cs
Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/ClientNetworkAnimator.cs.meta
README.md

This PR adds ClientNetworkAnimator to the samples utilities package.
[MTT-5025](https://jira.unity3d.com/browse/MTT-5025).
- [ N/A] Tests have been added for boss room and/or utilities pack

feat: Adding ClientNetworkAnimator to samples utilities package [MTT-5025]

---

.yamato/mobile-build-and-run.yml
Packages/manifest.json
Packages/packages-lock.json

This PR updates the test framework package and changes the bokken image used for building on android. This fixes issues with our CI jobs failing.

fix: yamato jobs failing because of unsupported bokken image

---

.yamato/mobile-build-and-run.yml

This PR updates the android bokken image used to run android tests during our CI to the latest supported version. It also removes the `--player-connection-ip=%BOKKEN_HOST_IP%` argument because the player connection is established over ADB on this image.
None
- [n/a] Release notes have been added to the [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file
- [n/a] JIRA ticket ID is in the PR title or at least one commit message
- [n/a] Include the ticket ID number within the body message of the PR to create a hyperlink

chore: update android bokken image for CI

---

CODE_OF_CONDUCT.md

updating broken link

---

CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
ProjectSettings/ProjectSettings.asset

This PR updates Boss Room project to version 2.1.0, and Utilities package to 1.6.0
[MTT-6292](https://jira.unity3d.com/browse/MTT-6292)

feat: Boss Room bundle version upgraded, changelogs updated [MTT-6292]

---

Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/package.json
Packages/packages-lock.json

This PR fixes an invalid dependency in the Utilities package
None

fix: fixing package dependency

---

CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md
Packages/com.unity.multiplayer.samples.coop/package.json
ProjectSettings/ProjectSettings.asset
README.md

This PR updates Boss Room's and the Utilities package's changelogs, as well as the project readme and the project and Utilities package versions.

feat: updating changelogs, readme and project version

---

.yamato/project-standards.yml
CHANGELOG.md

Fixing standards job by upgrading to a newer version of Python.
N/A

fix: yamato python version bump to fix standards job

---

.yamato/mobile-build-and-run.yml

fix: adding iOS phone model & env variable to build job

---

Assets/Editor/Tutorials/Homepage/0_TableOfContents.asset
Assets/Editor/Tutorials/Homepage/4_Resources.asset
Assets/Editor/Tutorials/Homepage/4_Resources.asset.meta
Assets/Editor/Tutorials/Images/Feature_Image_001.png
Assets/Editor/Tutorials/Images/Feature_Image_001.png.meta
Assets/Editor/Tutorials/Images/Feature_Image_003.png
Assets/Editor/Tutorials/Images/Feature_Image_003.png.meta
Assets/Editor/Tutorials/Images/Feature_Image_006.png
Assets/Editor/Tutorials/Images/Feature_Image_006.png.meta
Assets/Editor/Tutorials/Images/Icon_Authentication.png
Assets/Editor/Tutorials/Images/Icon_Authentication.png.meta
Assets/Editor/Tutorials/Images/Icon_Multiplayer_Services.png
Assets/Editor/Tutorials/Images/Icon_Multiplayer_Services.png.meta
Assets/Editor/Tutorials/Images/Icon_Vivox.png
Assets/Editor/Tutorials/Images/Icon_Vivox.png.meta
Assets/Editor/Tutorials/Resources.meta
Assets/Editor/Tutorials/Resources/4_HelpNGO.asset
Assets/Editor/Tutorials/Resources/4_HelpNGO.asset.meta
Assets/Editor/Tutorials/Resources/5_HelpUGS.asset
Assets/Editor/Tutorials/Resources/5_HelpUGS.asset.meta
CHANGELOG.md

This PR upgrades the In-Editor Tutorials with updated navigation, as well as updating URLs.
N/A
- [ N/A ] JIRA ticket ID is in the PR title or at least one commit message
- [ N/A ] Include the ticket ID number within the body message of the PR to create a hyperlink
- [ N/A ] An Index entry has been added in readme.md if applicable

feat: IET style cleanup: added resources, links updated
